### ISSUE TITLE
ReadTimeoutError(HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10))

### ISSUE THREAD

**Issue by natea** [openfun/richie-site-factory#300]
When I try to create the demo site, I get this error:

```
🐳(entrypoint) running your command: python manage.py create_demo_site
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "logo" %} in template courses/cms/category_detail.html.
  DuplicatePlaceholderWarning)
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "logo" %} in template courses/cms/organization_detail.html.
  DuplicatePlaceholderWarning)
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "portrait" %} in template courses/cms/person_detail.html.
  DuplicatePlaceholderWarning)
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "course_cover" %} in template courses/cms/course_detail.html.
  DuplicatePlaceholderWarning)
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "cover" %} in template courses/cms/blogpost_detail.html.
  DuplicatePlaceholderWarning)
/usr/local/lib/python3.7/site-packages/cms/utils/placeholder.py:255: DuplicatePlaceholderWarning: Duplicate {% placeholder "program_cover" %} in template courses/cms/program_detail.html.
  DuplicatePlaceholderWarning)
richie-site-factory_elasticsearch_1 is up-to-date
Creating richie-site-factory_dockerize_run ... done
2021/12/16 00:11:20 Waiting for: tcp://elasticsearch:9200
2021/12/16 00:11:20 Connected to tcp://elasticsearch:9200
Creating richie-site-factory_app-dev_run ... done
🐳(entrypoint) creating user running in the container...
🐳(entrypoint) running your command: python manage.py bootstrap_elasticsearch
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/management/commands/bootstrap_elasticsearch.py", line 29, in handle
    regenerate_indices(logger)
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/index_manager.py", line 80, in regenerate_indices
    list(map(lambda ix: perform_create_index(ix, logger), ES_INDICES)), ES_INDICES
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/index_manager.py", line 80, in <lambda>
    list(map(lambda ix: perform_create_index(ix, logger), ES_INDICES)), ES_INDICES
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/index_manager.py", line 59, in perform_create_index
    richie_bulk(indexable.get_es_documents(new_index))
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/index_manager.py", line 25, in richie_bulk
    stats_only=True,
  File "/usr/local/lib/python3.7/site-packages/richie/apps/search/elasticsearch.py", line 108, in bulk_compat_7_to_6
    bulk(client, actions, stats_only=stats_only, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 314, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 244, in streaming_bulk
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 130, in _process_bulk_chunk
    raise e
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 126, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 101, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1581, in bulk
    headers={"content-type": "application/x-ndjson"},
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 409, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 244, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=10))
ERROR: 1
make[1]: *** [search-index] Error 1
make: *** [demo-site] Error 2
```

**Comment by sampaccoud** [comment]
I seems that your Elasticsearch is not running. 
Try looking at the logs:
```bash
docker-compose logs elasticsearch
```

You most probably have this problem: https://github.com/openfun/richie/blob/master/docs/docker-development.md#troubleshooting
